[package]
name = "advent-of-code-2022"
version = "0.1.0"
authors = ["Max Davidson <davidsonmax@gmail.com>"]
edition = "2021"
license = "MIT"

[lib]
doctest = false

[dependencies]
itertools = "0.10.5"
lazy_static = "1.4.0"
regex = "1.7.0"

